### ISSUE TITLE
1기 개인 목표 작성

### ISSUE THREAD

**Issue by syohnet** [pro00er/improve-ourselves#1]
## 2020.12.02까지 단체 메신저방에서 나온 내용 정리
- 1기동안 집중할 작업 목표를 repo에 적는다
- 목표는 정량적, 구체적으로 적는다. 
  - 이번 기간에 달성할 수 있도록 작게 쪼개서 적는다
  - 타인이 결정해야 달성할 수 있는 목표는 잡지 않는다(예. repo star 100개 달성 (x) / 블로그 글 10개 작성(O))
- 목표는 달성하고 싶은 목적을 위해 해야하는 작업이다.

- [ ] issue comment 로 목표 적는다 due to ~2020.12.10.목 KST~ 2020.12.14.월 PM 12:00 KST 
- [ ] 다른 사람의 목표에 피드백해준다

**Comment by syohnet** [comment]
#5  - ohahohah 1기 목표

**Comment by kimsunoh** [comment]
#8 - kimsunoh 1기 목표

**Comment by syohnet** [comment]
각자가 초안이 나왔다면 README.md 에 내용 업데이트 해두는 거 어떨까요?

**Comment by syohnet** [comment]
related issue : 개인 목표 #4 #7 #8 #5

**Comment by syohnet** [comment]
1기 종료되었으므로 닫음.
