### ISSUE TITLE
SLiPP 모집글 작성

### ISSUE THREAD

**Issue by syohnet** [pro00er/improve-ourselves#10]
- 추가 인원을 모집하기 위해 SLiPP 모집글 작성 ~1/24

**Comment by kimsunoh** [comment]
공부해서 남주기

소개
개발자로써 다른 사람들이 써놓은 글만 소비하는 소비자일 때가 많았었습니다. 지난 스터디(마음을 담아 개발회고하기)에서 주기적인 회고를 하면서 기록을 하다보니 다른 분들은 어떤 것에 관심이 있는지, 나는 어떤 고민, 성장을 하면서 일을 하는지 의식적으로 생각할 수 있게 되었습니다.
 앞선 경험을 통해 기록이라는 것의 중요점을 알게되었습니다. 그래서, 올해는 갖고 있는 지식에 대해 정리하거나, 공부중인 것을 기록해서 다른 분들과 지식을 공유하려 합니다. 마냥 머리속에 담아두기 보다는 꺼내서 기록하고 주고받으며 같이 성장하고 싶습니다.

중요점
- 공부해서 남주기(이하:공남주)는 내가 공부한 것을 제대로 기록해서 공유하는 것에 의의를 두고 싶습니다. 기록하고 나만 본다면, 빠르고 간편하게 정리를 할 수는 있습니다. 그러나, 다른 사람에게 나중에 그 기록을 보여주려면, 그제서야 다른사람이 이해할 수 있는 말로 풀기에 힘이 들 수 있습니다. 이 스터디를 통해 지식 공급자가 되어 내가 쓰는 글을 한번더 꼼꼼히 살펴보고 의식적으로 모두가 볼 수 있는 기록을 하는 습관을 갖으려고 합니다
- 스터디를 통해 업무 외에 나를 위해 공부하는 습관을 들이려합니다. 공부하기전에 부담을 갖는다면 그 공부는 꾸준히 할 수 없을 것입니다. 그래서, 스터디에서는 부담없이 나에게 투자하는 하루 (최소) 30분을 고정으로하고, 매일 꾸준히 하는 것에 목적을 두고 싶습니다

예상 스터디원
- 함께 성장하고 싶은 사람
- 공부한 것을 기록하고 공유하고 싶은 사람
- 많은 양의 공부보다 적은 양의 공부라도 꾸준히 하고 싶은 사람

진행 방법
공부 방식
- 매일(주중 4회) 30분 자신이 편한시간에 공부하고, 공부 기록을 git에 공유합니다. (출석체크)
- 스터디 회고는 매주 1회 진행됩니다. 주간 공부에 대한 회고 혹은 다른 개발 관련된 이야기를 나눕니다.
- 주중에 출석체크일이 모자르다면 벌칙을 수행합니다. 벌칙은 스터디 시작때 참여자들에게 각 1개의 아이디어를 받고, 벌칙을 수행할때 랜덤으로 뽑기해서 정합니다. (벌칙을 추천받은 후 너무 어려운 벌칙이 있으면 2~3개 정도를 제외한다)
- 그 외 선호하는 회고/스터디 방법을 추천해주시면 반영해서 진행할 수 있습니다

**Comment by syohnet** [comment]
@kimsunoh 좋네요. 감사합니다

**Comment by syohnet** [comment]
슬립 위키 페이지가 열리면 해당 링크를 README.md 에 기록으로 남겨주실 수 있나요? @kimsunoh

**Comment by syohnet** [comment]
SLiPP 위키 페이지 정보 추가. 작업 완료.
