### ISSUE TITLE
목표 공유하기

### ISSUE THREAD

**Issue by louisJu** [pro00er/improve-ourselves#16]
- 기수별로 스스로 세운 목표를 작성하여 공유한다.

- Why? 작성후 타인에게 선언하므로써 조금 더 목표달성할 수 있도록 하기 위해서

## HOW
- 각자 모두가 하면 됩니다. 
- [ ] README.md 에 기수 목표 작성하기 [링크](https://github.com/pro00er/improve-ourselves#%EA%B0%9C%EC%9D%B8-%EB%AA%A9%ED%91%9C--%EA%B2%B0%EA%B3%BC%EB%AC%BC-%ED%8E%98%EC%9D%B4%EC%A7%80)
- 목표 주위에 공유하기 (선언효과) ex. 야 나 이거한다~

- [ ] 내가 어떻게 누구한테 공유했는지를 다음 회고 때 이야기해주세요.

**Comment by ohahohah** [comment]
나 공유했어요 이야기 다음 회고 때 해주세요.

**Comment by syohnet** [comment]
오랫동안 진행되지 않음. 2기 종료되었으므로 이슈 종료
