### ISSUE TITLE
2021-02-14 주간회고 기록 남기기

### ISSUE THREAD

**Issue by syohnet** [pro00er/improve-ourselves#27]
**실제로 중요한 일을 먼저 하자. 급한 일 말고, 정해진 일 말고.** 

- 주간 회고 기록을 README.md 2기 섹션에 남기기

----
**CheckList**
- [x] assignees , labels 확인하기
- [X] issue title 은 이슈를 요약하고 있나?
- [x] issue body는 issue body만 확인하고도 모르는 사람도 내용을 파악할 수 있을 정도로 적었나? (무엇을,언제,어디서)

**Comment by syohnet** [comment]
@impactrudia 
주간회고 기록을 남겨주실 수 있을까요? 
저는 회고 기록을 다른 링크 타고 가지 않고 바로 볼 수 있게 링크 대신 로그를 남기는 것도 좋다고 생각해요. 
slipp wiki 기록 링크를 남기면 두 번 로그 남기는 작업을 하지 않아도 되어서 간편해 보이고요. 

이번에는 편한 방법대로 작업해주세요.

**Comment by impactrudia** [comment]
> @impactrudia
> 주간회고 기록을 남겨주실 수 있을까요?
> 저는 회고 기록을 다른 링크 타고 가지 않고 바로 볼 수 있게 링크 대신 로그를 남기는 것도 좋다고 생각해요.
> slipp wiki 기록 링크를 남기면 두 번 로그 남기는 작업을 하지 않아도 되어서 간편해 보이고요.
> 
> 이번에는 편한 방법대로 작업해주세요.

 slipp wiki 기록 링크라는게 어떤걸 말하는걸까요?

**Comment by syohnet** [comment]
https://www.slipp.net/wiki/plugins/servlet/mobile?contentId=52528721#content/view/52528721 슬립에 올린 2주차 회고 링크요~

**Comment by syohnet** [comment]
공남주 태그도 붙여주세요~ 
![image](https://user-images.githubusercontent.com/17819874/108599437-75b52980-73d4-11eb-98ab-7c16110b05ce.jpeg)

**Comment by syohnet** [comment]
@impactrudia 작업을 완료하여 이슈를 종료합니다.
