### ISSUE TITLE
[1기 목표] Rudia Moon

### ISSUE THREAD

**Issue by syohnet** [pro00er/improve-ourselves#4]
- 목표 : 위치기반 이론 및 안드로이드 최신 대응전략 블로그 정리
- 결과물 :  티스토리에 공유할 계획
- 중간 과정 : [노션에 기록](https://www.notion.so/rudiamoon/GPS-f79a1a5cc953491a93a5a7a6964f15a8)
- 대략적인 작업 계획 : 
- 각 task  별 예상 시간:
 - 위치기반 이론정리 (4h) 
   -  GPS 수집과정
   - 도면 내용 정리
     - 모르는 내용 정리
   - 삼각측량법이란
 - 위치 수집 (4h)
 - 실제로 적용하면서 느꼈던 팁들 (4h)
### 2021MMDD
  - KEEP :
  - PROBLEM :
  - TRY : 
 ### 20210105
  - KEEP : 읽었던 자료 토대로 중간과정을 노션에 적기로 했다. 적으려고 생각할 땐 어려웠는데 막상 적으면서 하니 또 재미있다.
  - PROBLEM : 월요일마다 제시간에 못하는 것 같다. 
  - TRY : 목요일 휴식 대신 화-금 이렇게 해보는 건 어떨까?
 ### 20201229
   - KEEP : 선오 시작 알림 좋았다, 적을 내용 구체적으로 정리하니 내가 쓸 내용이 보였다. 기존 찾았던 자료들을 링크를 모아가는 과정을 했다.
 ### 20201228
   - KEEP : 이론만 읽다가 오늘은 노트에 이해가 필요한 부분은 적으면서 해봤다. 집중이 훨씬 잘 되는 것 같다.
   - PROBLEM : 잘하고 있는건지 모르겠다.
   - TRY : 글을 써야할 내용에서 서론 본론 결론에 들어갈 내용을 생각해보고 더 세부적을 찾아봐야겠다.
 ### 20201223
   - KEEP : 미리 일어나서 회고준비하기
   - PROBLEM : 아침에 일어나서 하는거 적응하는데도 시간이걸리고 이번엔 이론 제대로 알고싶음데 예상 진도가 느림. 
   - TRY : 일정을 변경해야겠다

**Comment by syohnet** [comment]
@impactrudia 작업하고 계시는 내용 같이 공유해주시면 좋겠네요!

**Comment by impactrudia** [comment]
> @impactrudia 작업하고 계시는 내용 같이 공유해주시면 좋겠네요!

계속 데이터만 찾고 있어서요!
앞으론 공유하도록하겠습니다.

**Comment by syohnet** [comment]
1기 종료됨. issue 닫음
