### ISSUE TITLE
[1기] 목표 - ohahohah 

### ISSUE THREAD

**Issue by syohnet** [pro00er/improve-ourselves#5]
## 목표 및 결과물
- 목표 : 1년 동안 해왔던 개발 관련 활동별로 회고 블로그 작성
- 결과물 : [ohahohah.com - 개인 blog post](https://ohahohah.com)

## 대략적인 작업 계획 (각 task 별 예상 소요시간)
- 글 작성할 topic 뽑아내기
- post 별 관련 자료 모으기
- post 작성
- post 작성 후 경험 회고 기록

## 확인해야하는 것
- 아직 블로그 작성을 구조화해본 적이 없어서 예상 소요시간 적기가 어려움. 예상시간과 실제 소요시간 측정하면서 gap 줄여나가야함
- 글을 작성할 때, chunk 시간이 너무 짧으면 집중 안될 듯. 최소 chunk 가 어느 정도인지 관찰하는 것도 의미가 있겠다.

## Next Action 
- [ ]  [for topic들 뽑아내기] 올해 활동 중에 회고하고 싶은 거 list up
- [ ]  팀원들에게 위 자료 피드백 요청 @kimsunoh @impactrudia @louisJu
- [ ] 이 활동에 12,1월 일주일에 어느정도 시간을 낼 수 있는지 적기

**Comment by louisJu** [comment]
하루에 한개의 post 작성이 목표인건가요~?
topic에는 기술적인 내용도 포함되나요~?

post는 짧게 쓴다고해도 오래 걸리는 것 같아서요 ㅠ (저는 초고 작성(시간오래걸림) -> 수정(또 오래걸림) -> 게시(그냥고민 많이함) 이 루틴이라서 오래 걸리는데 시영님은 어떻게 작성해서 upload 하시는지 궁금합니다 ㅎㅎ )

**Comment by syohnet** [comment]
기술 topic 에 대해서는 다루지 않을 예정이고요. 저희 slipp회고 마지막 시간 총 회고 했던 것처럼 어떤 활동을 했고 어땠고 어떻게 개선을 할지 등에 초점을 맞추려고 합니다. 

저는 두 가지로 갈리는 거 같아요. 어떨 때는 한 번에 시간 잡고 처음부터 쭉 쓰고 올리거나 
하루에 조금씩 만들면서 작성해나가거나 해요. 
제 TIL 에서 내용 모으는 작업하고 그 이후에 이 정도면 되었다 싶으면 blog로 옮기고 게시한 후에 이걸 퇴고하는 스타일이에요. 하다보면 끝도 없어서 마감 시간을 정해놓고 할 때도 있고요.

**Comment by syohnet** [comment]
## 정리 글감 토픽
- 퇴사 이후 1년동안 어떤 일이 있었나?
- 웹 기초 수업 커리큘럼 만든 이야기
- SLiPP 회고 마지막 회고 글 
- 온라인 모각코로 일하기
- 개발자와 튜터 사이
  - 강의 1. 커리큘럼 없이 프로젝트 뛰어들기 
  - 강의 2. 팀으로 서로에게 가르치기
  - 강의 3. 프로젝트에 맞게 topic 배우기

**Comment by syohnet** [comment]
1기에 작업 안했고 3기 목표로 가져갈 것.

**Comment by syohnet** [comment]
3기 목표 할 때 새로 issue 연다. 1기 끝났으니 닫는다.
