### ISSUE TITLE
[1기 목표] louisJu

### ISSUE THREAD

**Issue by louisJu** [pro00er/improve-ourselves#7]
목표 : 우아한테크캠프Pro 미션수행, 피드백 정리, 강의내용 정리 + 관련 학습내용 정리

결과물 : 매 미션 별 피드백 및 코드 리펙토링과정을 기록 + 관련 학습내용 정리

## 대략적인 작업 계획 (1주일)
미션이 끝날때마다 단계별로 받았던 피드백 및 리펙토링 코드들을 조각을 쪼개서 기록 (전체 코드는 개인 github repo)
미션 회고 
강의내용 정리 
미션 관련 학습한 내용 정리

## 고민사항
매주 미션에 매일 시간을 투자하고 있지만 고정적이지 않음. 
미션 진행은 기존대로 유동적으로(코딩 -> 피드백 -> refactoring) 진행하고 고정적으로 매일 개인공부시간을 가지는게 어떨까 싶음.
=> 개인학습은 따로 진행
주차별 강의내용 정리 + 미션 회고를 posting 하는데 시간이 얼마나 걸릴지 모르겠음 (측정해봐야 할듯)

## Next Action
이번주(12/14 ~ 12/16)에 1,2주차 내용 정리 진행하면서 timeCheck 
고정적으로 투자할 시간 정하기
어떤 공부를 할것인지 정하기
매주 강의내용 + 미션회고 posting deadline을 언제로 할지 정하기.

**Comment by syohnet** [comment]
오 지금 집중하고 있는 작업의 연장선상이군요. code 조각을 잘 보여줄 수 있는 플랫폼이 쓰기 편하실 수 있겠네요. 

https://github.com/woowacourse/javable/ 이 프로젝트 재밌게 봤었는데 뭔가 이런 느낌이 들기도 하고요. 강의내용이 궁금하네요!

**Comment by syohnet** [comment]
1기 종료됨. issue 닫음
